### ISSUE TITLE
Lyrebird stops responding on opening Pulseaudio Volume control.

### ISSUE THREAD

**Issue by hakanohi** [chxrlt/lyrebird#1]

**Comment by chxrlt** [comment]
Could you please give more information on this? I have tested on Arch, and found no issues

**Comment by harrego** [comment]
pavucontrol probably needs to be called as a [detached process](https://stackoverflow.com/questions/51538651/how-to-detach-a-program-ran-by-subprocess-call) rather than being tied to Lyrebird

**Comment by hakanohi** [comment]
Distro: Ubuntu 20.04
Python version: 3.8.2

![lyrebird](https://user-images.githubusercontent.com/51394064/90014324-96ceec00-dcc6-11ea-9f11-ff4081c66b1b.png)

Lyrebird is responsive once Pulseaudio Volume control is closed.

**Comment by harrego** [comment]
I have this bug too on Ubuntu 20.04, I could never figure out what caused it! I’m gonna work on a fix

**Comment by hakanohi** [comment]
Maybe launching pauvcontrol as a modal to the lyrebird window would help solve it.

**Comment by chxrlt** [comment]
Hopefully this should be fixed in the latest commit. Thanks @harrego @hakanohi for reporting this issue
