### ISSUE TITLE
Lyrebird virtual input device not detecting sound

### ISSUE THREAD

**Issue by psppwner300** [chxrlt/lyrebird#10]
After installing the application and ensuring the requirements are installed as well, setting the input device as "Lyrebird virtual input" won't pick up any sound from the mic.

If it helps, I'm using the [HyperX Quadcast](https://www.amazon.com/gp/product/B07NZZZ746/ref=ppx_yo_dt_b_asin_title_o08_s02?ie=UTF8&psc=1) and Pop!_OS 20.04.

**Comment by harrego** [comment]
![pavucontrol screenshot](https://user-images.githubusercontent.com/41309736/90156370-4322d800-dd84-11ea-8eee-bad87bb63c12.png)
In `pavucontrol` (from any distro repo) have you set "SoX" to use your microphone? "Built-in audio analogue stereo" in my case.

**Comment by psppwner300** [comment]
Initially I didn't see `SoX` under the Recording section. I noticed you had just added `libsox-fmt-pulse` in the requirements section in the `readme`; after installing that and restarting the machine it showed up and now it works. Just seems to be a delay after talking; not sure if that's intentional or not.

**Comment by zaggynl** [comment]
For reference, on OpenSUSE this package is named 'sox' and is available here: https://software.opensuse.org/package/sox

**Comment by john-cena-141** [comment]
I can't find `libsox-fmt-pulse' on Manjaro

**Comment by Dudecake** [comment]
> I can't find `libsox-fmt-pulse' on Manjaro

In Debian (derivatives) `libsox_fmt_pulseaudio.so` is packaged in a separate package, in Arch (derivatives), Fedora and probably more `libsox_fmt_pulseaudio.so` is part of the main sox package.

**Comment by john-cena-141** [comment]
I already have sox installed. Did a reboot and there is no Sox on PulseAudio Volume Control
