### ISSUE TITLE
Mention libsox-fmt-pulse as a necessary dependency on Debian systems

### ISSUE THREAD

**Issue by chloecormier** [chxrlt/lyrebird#11]
At least on Debian/Ubuntu, when installing the necessary dependencies, installing `sox` doesn't pull in its support for PulseAudio, and Lyrebird will silently fail with `sox FAIL formats: no handler for given file type 'pulseaudio'`

Adding a dependency for `libsox-fmt-pulse` would help Debian/Ubuntu users figure out what they're missing in this case.

**Comment by harrego** [comment]
Done! We really appreciate the suggestion! :)

**Comment by marcopik** [comment]
![2469250-dc8229a3387be6cd1f8603027758abf9 — kopia](https://user-images.githubusercontent.com/107511933/173684531-b57914d8-5b51-44d9-bdfe-f2e6c0c4ced8.jpg)
@chloecormier is male in wig transvestite paedophile from tf2 classic who wears wig and takes female hormones to trick kids into being raped, but dont worry they look like male they will get beaten to death assuming they dont suicide first :)
