### ISSUE TITLE
Do not use /etc for config files

### ISSUE THREAD

**Issue by dpanter** [chxrlt/lyrebird#12]
Strongly suggest using a proper directory e.g. `$HOME/.config/lyrebird` for the config files.

Using `/etc` this way is not desirable nor complying with XDG Base Dir spec.

**Comment by harrego** [comment]
Lyrebird config and presets can be overridden by placing files in `~/.config/lyrebird`, `/etc/lyrebird` serves as a global and customizable default. What would be your suggestion instead?

**Comment by dpanter** [comment]
Seems there's already a solution as per the PR noted in #19 :)

**Comment by harrego** [comment]
Fixed in commit 57ffdf7
