### ISSUE TITLE
Linux Mint: Failed to open file 'icon.png': No such file or directory (4)

### ISSUE THREAD

**Issue by calexil** [chxrlt/lyrebird#14]
jd@Marzipan:$ python3.7 /usr/local/bin/lyrebird/app.py
Module module-null-sink not loaded.
Module module-remap-source not loaded.
Traceback (most recent call last):
  File "/usr/local/bin/lyrebird/app.py", line 18, in <module>
    win = mainwindow.MainWindow()
  File "/usr/local/bin/lyrebird/lyrebird/mainwindow.py", line 54, in __init__
    self.set_icon_from_file('icon.png')
**GLib.Error: g-file-error-quark: Failed to open file 'icon.png': No such file or directory (4)**
jd@Marzipan:$

**Comment by chloecormier** [comment]
It looks for the file in the same directory that the terminal is in when you run it, so if you first cd to /usr/local/bin/lyrebird and then start it, it works fine. I'd say this is still an issue though, it shouldn't be dependent on where you run it from.

**Comment by harrego** [comment]
This should be a simple fix by prefixing `icon.png` with the working directory. I'll put in a fix at some point but anyone is free to beat me to it :-)

**Comment by harrego** [comment]
Fixed in PR #19
