### ISSUE TITLE
Voice changer will not change voice when turned on, and it will play back your voice even when off and closed.

### ISSUE THREAD

**Issue by A-Random-Lantern** [chxrlt/lyrebird#15]
I've selected the voice changer in the voice recorders and yet I can still hear my voice when playing it back.

Pop!_OS 20.04 is my OS

**Comment by chxrlt** [comment]
Hey, sorry to hear you are having issues with this. could you please provide more information, like your python version, and did you install the packages required (listed in README)?

\- Charlotte

**Comment by A-Random-Lantern** [comment]
Nvm, turns out I didn't see the required packages. Sorry
