### ISSUE TITLE
Linux mint (Cinnamon): error when trying to run the app.py

### ISSUE THREAD

**Issue by Roman-Os** [chxrlt/lyrebird#17]
After a normal install, app.py in usr/local/bin/lyrebird gives this error when trying to run with python3

```
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    import lyrebird.mainwindow as mainwindow
ModuleNotFoundError: No module named 'lyrebird.mainwindow'
```

**Comment by harrego** [comment]
This is usually a permission issue, could you run `sudo chmod -R 755 /usr/bin/lyrebird /etc/lyrebird` and see if that fixes the issue?

If the issue still occurs then please could you run `sudo ls -la /usr/bin/lyrebird/lyrebird` and post the output.

**Comment by Roman-Os** [comment]
That works, thanks.
