### ISSUE TITLE
no module named dataclasses

### ISSUE THREAD

**Issue by Antiswitcher** [chxrlt/lyrebird#20]
after an attempted install, all dependencies were double checked to be installed. 

lafont@lafont-G3-3579:~/Desktop/lyrebird-master$ ./Lyrebird.desktop
./Lyrebird.desktop: line 1: [Desktop: command not found
./Lyrebird.desktop: line 6: Changer: command not found
Traceback (most recent call last):
  File "/usr/local/bin/lyrebird/app.py", line 5, in <module>
    import lyrebird.mainwindow as mainwindow
  File "/usr/local/bin/lyrebird/lyrebird/mainwindow.py", line 10, in <module>
    import lyrebird.core.presets as presets
  File "/usr/local/bin/lyrebird/lyrebird/core/presets.py", line 4, in <module>
    import lyrebird.core.config as config
  File "/usr/local/bin/lyrebird/lyrebird/core/config.py", line 3, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

**Comment by epicfacethe3rd** [comment]
i'm having this same issue

**Comment by epicfacethe3rd** [comment]
this issue appears for me to be related to a bad python version on ubuntu as this comment suggests
https://github.com/chxrlt/lyrebird/issues/9#issuecomment-673584074
i'm going to try to get it to run python 3.7 and see if that fixes it

**Comment by harrego** [comment]
Hey guys, dataclasses are a Python 3.7 feature so updating should fix your issue. I'm going to update the requirements to mention that.

**Comment by epicfacethe3rd** [comment]
running it under python 3.7 did not fix the issue
`epic@desktop:/usr/local/bin/lyrebird$ python3.7 app.py
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from 'gi' (/usr/lib/python3/dist-packages/gi/__init__.py)`

**Comment by epicfacethe3rd** [comment]
additonaly, `python3.7 --version` says i am on python 3.7.5

**Comment by harrego** [comment]
@epicfacethe3rd Your issue appears to be with gi/gobject not your Python version, please see issue #13 and let me know if that fixes it.

**Comment by epicfacethe3rd** [comment]
@harrego yep, that fixed it. thanks!

**Comment by harrego** [comment]
@epicfacethe3rd Awesome! :)
