### ISSUE TITLE
Have proper distro packages available

### ISSUE THREAD

**Issue by dominikaaaa** [chxrlt/lyrebird#21]
Having an install script is eh and means you have to manually update. 

Having an AUR package along with a Ubuntu package available (ppa for ubuntu) would make it more accessible and that should satisfy the majority of mainstream distro users.

**Comment by aosync** [comment]
I should be able to make and publish a KISS package when I get back from vacations.

**Comment by harrego** [comment]
I totally agree, pip3, Ubuntu and Arch are all essential.

**Comment by harrego** [comment]
Added in v1.1.0, check the README for more details :-)
