### ISSUE TITLE
Can't launch it

### ISSUE THREAD

**Issue by IssouLinux** [chxrlt/lyrebird#23]
Sounds fun, but unfortunately I can't try.

./install.sh

/usr/local/share/applications/ didn't exist before, just created it

Installing required pip3 modules

Defaulting to user installation because normal site-packages is not writeable

Requirement already satisfied: toml in /home/seifer/.local/lib/python3.6/site-packages (0.10.1)

Installed Lyrebird to /usr/local/bin/lyrebird/

Installed Lyrebird.desktop to /usr/local/share/applications/

Lyrebird does is in my applications list, but nothing happens when I click on it. Any idea?

**Comment by epicfacethe3rd** [comment]
if you're on ubuntu it requires python 3.7
but installing python 3.7 hasn't solved the issue for me on ubuntu
https://github.com/chxrlt/lyrebird/issues/20
if you go to /usr/local/bin/lyrebird and run `python3 app.py` you should likely get the same issue

**Comment by harrego** [comment]
As @epicfacethe3rd said Lyrebird requires Python 3.7+, updating should fix the issue but let me know if you still can't launch.
