### ISSUE TITLE
Don't allow for two instances of Lyrebird to be open

### ISSUE THREAD

**Issue by developedby** [chxrlt/lyrebird#25]
Lyrebird creates a pulseaudio sink and source with fixed name. Opening two instances of the program makes them compete for the same resources and basically everything breaks.

There should be some check if Lyrebird is already open, and maybe show a warning to the user in case it is.

**Comment by chxrlt** [comment]
I agree, this is a bad idea and there should be a check in place. We will add a check in place as soon as possible, since having two versions of it opens causes issues.

**Comment by harrego** [comment]
Added in commit 83f0808. Thanks for the suggestion!
