### ISSUE TITLE
Deb/PPA packaging/repo?

### ISSUE THREAD

**Issue by BloodyIron** [chxrlt/lyrebird#29]
Any chance we can get releases with deb packaging, and/or a PPA/repo?

I really avoid software that my package manager is unaware of like the plague, so if you would be so kind as to expand your build and release process to deb packaging at a minimum, or go beyond that into running a PPA/repo, that would be very much appreciated! And I'm sure by far more than just me. :)

**Comment by harrego** [comment]
v1.1 will have packages in most major repos and should be done in the next few days. I'll keep this issue updated with progress.

For anyone reading on Arch and wondering the same, there is currently a community AUR package under [lyrebird](https://aur.archlinux.org/packages/lyrebird)

**Comment by D3SOX** [comment]
Hi I'm the current maintainer of the AUR package. If one day you want to take over the package or become a co-maintainer you can contact me :wink:

**Comment by harrego** [comment]
h@harry.city is me, harrego, and 6CEFEA5076D2C1D5F3834C48C0B32F643D918E25 is my PGP key.
```
-----BEGIN PGP SIGNATURE-----

iQGzBAABCgAdFiEEbO/qUHbSwdXzg0xIwLMvZD2RjiUFAl9K2lQACgkQwLMvZD2R
jiVT3wv+JoYqpsf6TB7I6TrY1qUxPrjavOUSd9fck2oPnFf9J3DG8d3pX4ohYwGk
/xUUfyOzo1hriQ8VpdOoYHsd5ThUdldxLR9lIXBtXoAbOGhmyVEeXYF4KmF0uJtA
QHip4lyCOQoCHt9EixTs3anpx+5uqmw63QQPvztrd4XoypFzKSAfZNkSI8Ri2uGo
EhrqZGId3MI7IjQS+aNBUkFFHb63qd3H8m8Og+JJYA8yVPHSSYDcYXfwPAoprU3d
QHwIvNnOmtK1o3EoEVj0P8D6jRZYIGfQHHtJYU2yRKsHxdC9Kf8tafOueHMaBzvI
rcnPr21z8dx3EhRxvbUNmpPLJ1jGaBzsUT5x2gu+Os7IdvDBbgZW2o5Hlk/5nFJY
R4w+BlMjiQ90+r3+6N0zek7RLysIoW5ViF8wkeOpWNTMdbSbDV+KCqO4ad2/rDDH
rQ3eeaiNVWU19CHHc3OMynbJLjIfEQa6lZ96cSk1eWZJpjUK+41NlT8Oj+Jst1dY
eXSNifRu
=A698
-----END PGP SIGNATURE-----
```

**Comment by harrego** [comment]
Added in v1.1.0, check the README for more details :-)

**Comment by BloodyIron** [comment]
Thanks! :D
