### ISSUE TITLE
Missing implicit dependency gi

### ISSUE THREAD

**Issue by aosync** [chxrlt/lyrebird#36]
While attempting to package lyrebird for kiss, I have come across the problem that `gi` is missing. After some search it apparently can be installed from the pygobject package provided [there](https://gitlab.gnome.org/GNOME/pygobject).

Wouldn't it be wise to explicitly state it as a dependency?

**Comment by chxrlt** [comment]
doesn't the readme state that `python-gobject` is a required dependency? if not, then please let me know and we will add it

/- charlotte

**Comment by harrego** [comment]
gi/pygobject is an annoyingly loose dependency that seems to be different on every distribution but it is listed in the README
