### ISSUE TITLE
Kubuntu 20.04 - bad .desktop

### ISSUE THREAD

**Issue by WesR** [chxrlt/lyrebird#40]
The environment variables are not set by default, causing the application not to launch. Also, just having the category "audio" does not add it to the multimedia category, and instead places it into "lost and found". Below is a working config for me. 

```[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Name=Lyrebird
GenericName=Voice Changer
Icon=/usr/share/lyrebird/icon.png
Exec=/usr/bin/lyrebird
Path=/usr/share/
Terminal=false
Categories=AudioVideo;Audio;
```

**Comment by harrego** [comment]
Thanks for this, I'll merge it into the master branch soon. Can I ask what you meant by "environment variables are not set by default" though? To my knowledge Lyrebird doesn't require any environment variables to launch.

**Comment by WesR** [comment]
The icon, exec, and path part of the .desktop currently use bash variables. This is the current one 
```
Icon=${SHARE_PATH}/icon.png
Exec=${BIN_PATH}/lyrebird
Path=${SHARE_PATH}/

```

**Comment by harrystanton** [comment]
@WesR The `.desktop` in the master branch is a template to be used with the installer script, each distro package also ships with a modified version. Agreed its not clear enough and will add a note to the README.

**Comment by harrego** [comment]
@WesR The `.desktop` in the master branch is a template to be used with the installer script, each distro package also ships with a modified version. Agreed its not clear enough and will add a note to the README.

**Comment by WesR** [comment]
Sounds good. I would recommend that `Categories=AudioVideo;Audio;` gets updated in the template.

Also, that the variables be replaced in the .deb build.

**Comment by harrego** [comment]
> Also, that the variables be replaced in the .deb build.

Total screw up on my part! Fixed now, thanks for flagging!
