### ISSUE TITLE
All my null sinks disappeared.

### ISSUE THREAD

**Issue by Esper89** [chxrlt/lyrebird#41]
Every time I turn lyrebird on, all my null sinks disappear and my loopback devices that were using those null sinks get set to use the wrong sinks.

**Comment by chxrlt** [comment]
The null sink disappearing is intended behavior, since Lyrebird unloads **all** null sinks to prevent redirecting output to the wrong one. Cannot comment on the loop back device thing, but as of now there is no fix to this being implemented.
