### ISSUE TITLE
Load config from /etc by default

### ISSUE THREAD

**Issue by C0rn3j** [chxrlt/lyrebird#6]
It'd be nice to try loading the needed config files from /etc/lyrebird and then override them by ~/.config/lyrebird if they exist there.

I wanted to throw it on AUR but this is making it hard.

**Comment by chxrlt** [comment]
sure, we will do this in half an hour or something :)

**Comment by harrego** [comment]
@C0rn3j I've made the change in v1.0.1 (369a7e8), let me know if this works for you.
