### ISSUE TITLE
Created config file as root

### ISSUE THREAD

**Issue by marissa999** [chxrlt/lyrebird#7]
I just installed the program through the install.sh (without sudo, but I configured sudo to not ask for a password when needed). After testing it in the Discord audio settings I realised that there is a unexpected high delay. Therefore I wanted to adjust the config file. But trying to edit the config file normally resulted in no permissions. Checking the permissions and ownership returned the following: 
`[13/08/20 2:14:32] littles@yui ~/lyrebird (master) $ ls -lah ~/.config/lyrebird/config.toml`
`-rw-r--r-- 1 root root 238 Aug 13 12:46 /home/littles/.config/lyrebird/config.toml`
Seems like its 544 as root:root? I assume that is a mistake?

**Comment by harrego** [comment]
This is an install bug fixed in v1.0.1, running `sudo chown -R littles:littles /home/littles/.config/lyrebird/` should fix this for v1.0.0. Let me know if this works!

**Comment by marissa999** [comment]
Yeah that fixed it for me. Seems like I just installed the program right before v1.0.1, that is unlucky 🙃 Thanks and thank you for the tool!
