### ISSUE TITLE
Blindly pkilling sox is a bad idea

### ISSUE THREAD

**Issue by chxrlt** [chxrlt/lyrebird#8]
Blindly pkilling sox is a bad idea. Especially since it's possible that a user could have multiple instances of sox running, and when he/she closes Lyrebird then all of the other instances of sox get killed too. An alternative would be to look into terminating the `subprocess` properly

**Comment by hunternet93** [comment]
When you run `subprocess.Popen`, it returns a [Popen object](https://docs.python.org/3/library/subprocess.html#popen-objects) on which you can call `kill()` to kill its attached process. Just store a reference in your MainWindow class and add a function to run `kill`:

```python
class MainWindow:
  def whatever_makes_sox(self):
    self.sox_proc = subprocess.Popen(whatever)

  def cleanup(self):
    if self.sox_prox:
      self.sox_proc.kill()
```

Then add a global try/except handler wrapping your `Gtk.main()`, for example:

```python
try:
  Gtk.main()
except BaseException e:
  win.cleanup()
```

(Catching `BaseException` means it'll also catch `KeyboardInterrupt`, `SystemExit`, and a few others that don't inherit from `Exception`)

I'm not on my dev machine right now so can't make a PR, but I think that should do it.
